"""fix

Revision ID: c2886f05d083
Revises: 
Create Date: 2024-09-16 00:31:46.582702

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c2886f05d083'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.alter_column('encrypted_vote',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.LargeBinary(),
               existing_nullable=False)
        batch_op.drop_constraint('votes_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('votes_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('votes_ibfk_3', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('votes_ibfk_3', 'elections', ['election_id'], ['id'])
        batch_op.create_foreign_key('votes_ibfk_2', 'candidates', ['candidate_id'], ['id'])
        batch_op.create_foreign_key('votes_ibfk_1', 'users', ['user_id'], ['id'])
        batch_op.alter_column('encrypted_vote',
               existing_type=sa.LargeBinary(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
